// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irzozsauyvtlrhfnnvjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyem96c2F1eXZ0bHJoZm5udmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzE1MTksImV4cCI6MjA3MzYwNzUxOX0.o_lGICVJeEUBHV6ciBJehCzUahHhjW-aDsNv1QT-Roo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});